version: '3.8' # if no version is specificed then v1 is assumed. Recommend v2 minimum

networks:
  k8stesting.io:
    name: k8stesting.io

services:
  ansible-c:
    hostname: ansible-c
    container_name: ansible-c
    image: ubuntu:latest
    ports:
     - ${ANSIBLEC_PORT_SSHD}:22
     - ${ANSIBLEC_PORT_TTYD}:8681
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/ansible-c/ansible:/home/ansible
     - ${ANSIBLE_HOME}/ansible-c/root:/root
    networks:
     - k8stesting.io

  k8stest1:
    hostname: k8stest1
    container_name: k8stest1
    image: ubuntu:latest
    ports:
     - ${K8STEST1_PORT_SSHD}:22
     - ${K8STEST1_PORT_TTYD}:8682
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/k8stest1/ansible:/home/ansible
     - ${ANSIBLE_HOME}/k8stest1/root:/root
    networks:
     - k8stesting.io

  k8tstest2:
    hostname: k8stest2
    container_name: k8stest2
    image: ubuntu:latest
    ports:
     - ${K8STEST2_PORT_SSHD}:22
     - ${K8STEST2_PORT_TTYD}:8683
    privileged: true
    volumes:
     - ${CONFIG}:/config
     - ${ANSIBLE_HOME}/shared:/shared
     - ${ANSIBLE_HOME}/k8stest2/ansible:/home/ansible
     - ${ANSIBLE_HOME}/k8stest2/root:/root
    networks:
     - k8stesting.io

#  centos1:
#    hostname: centos1
#    container_name: centos1
#    #image: spurin/diveintoansible:centos
#    image: spurin/diveintoansible:centos-sshd-2222
#    ports:
#     - ${CENTOS1_PORT_SSHD}:22
#     #- ${CENTOS1_PORT_SSHD}:2222
#     - ${CENTOS1_PORT_TTYD}:7681
#    privileged: true
#    volumes:
#     - ${CONFIG}:/config
#     - ${ANSIBLE_HOME}/shared:/shared
#     - ${ANSIBLE_HOME}/centos1/ansible:/home/ansible
#     - ${ANSIBLE_HOME}/centos1/root:/root
#    networks:
#     - diveinto.io

    # Canonical bridge interface name
    #
    # The setting below provides a friendly name for the bridge interface
    # as seen in the likes of the ip command.  Use at your own discretion
    #
    #driver_opts:
    #  com.docker.network.bridge.name: "diveinto.io"
