apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rep-controller
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
        - name: nginx-pod
          image: nginx
  replicas: 3
