---
containerd_version: 1.6.8-1
k8s_version: 1.25.0-00
#containerd_version: 1.6.6-1
#k8s_version: 1.22.3-00
#k8s_version: 1.24.3-00

#
# When set to TRUE/true the vxlan overlay is installed.
# When set to FALSE/false the IPIP overlay is installed.
#
vxlan: false


apt_keys:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
  - https://download.docker.com/linux/ubuntu/gpg

apt_repos:
  - filename: kubernetes
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
  - filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

kernel_modules:
  - overlay
  - br_netfilter

kubernetes_packages:
  - "kubelet={{ k8s_version }}"
  - "kubeadm={{ k8s_version }}"
  - "kubectl={{ k8s_version }}"
  - "containerd.io={{ containerd_version }}"

os_packages_all:
  - apt-transport-https
  - bridge-utils
  - ca-certificates
  - chrony
  - curl
  - gnupg-agent
  - ipset
  - net-tools
  - software-properties-common
  - sshpass
  - sysstat
  - tree
  - vim

sysctl_settings:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1

host_entries:
    - '10.0.1.131 controller-01 kube-master'
    - '10.0.1.132 controller-02'
    - '10.0.1.133 controller-03'
    - '10.0.1.134 worker-01'
    - '10.0.1.135 worker-02'
    - '10.0.1.136 worker-03'
    - '10.0.1.137 worker-04'
    - '10.0.1.130 kubelb-01'
    - '192.168.60.131 controller-01-priv'
    - '192.168.60.132 controller-02-priv'
    - '192.168.60.133 controller-03-priv'
    - '192.168.60.134 worker-01-priv'
    - '192.168.60.135 worker-02-priv'
    - '192.168.60.136 worker-03-priv'
    - '192.168.60.137 worker-04-priv'
    - '192.168.60.130 kubelb-01-priv'
