---
containerd_version: 1.5.10-1
k8s_version: 1.21.3-00
#containerd_version: 1.6.6-1
#k8s_version: 1.24.3-00

kubernetes_packages:
  - "kubelet={{ k8s_version }}"
  - "kubeadm={{ k8s_version }}"
  - "kubectl={{ k8s_version }}"
  - "containerd.io={{ containerd_version }}"

os_packages_all:
  - apt-transport-https
  - ca-certificates
  - chrony
  - curl
  - gnupg-agent
  - net-tools
  - software-properties-common
  - sshpass
  - sysstat
  - tree
  - vim

sysctl_settings:
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
