apiVersion: v1
kind: Pod
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler2
  namespace: kube-system
spec:
  containers:
    - command:
        - /usr/local/bin/kube-scheduler
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=my-scheduler2
      image: k8s.gcr.io/kube-scheduler-amd64:v1.21.4
      name: my-scheduler2-pod
  resources:
