version: '3.7'

services:

  redis-server:
    image: redis:latest
  node-app:
    build: .
    ports:          # Port mapped is just for access from our local machine.
      - "4001:8081"
    restart: always
