apiVersion: v1
kind: Pod
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler
  namespace: kube-system
spec:
  containers:
    - command:
        - /usr/local/bin/kube-scheduler
        - --address=127.0.0.1
        - --leader-elect=false
        - --scheduler-name=my-scheduler
      image: k8s.gcr.io/kube-scheduler:v1.21.12
      name: my-scheduler
  resources:
