apiVersion: v1
kind: Pod
metadata:
  name: custom-scheduler
  namespace: kube-system
  labels:
    component: kube-scheduler
    tier: control-plane
spec:
  containers:
    - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        #- --bind-address=127.0.0.1
        - --address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=false
        - --scheduler-name=custom-scheduler
        - --lock-object-name=custom-scheduler
      image: k8s.gcr.io/kube-scheduler-amd64:v1.21.4
      name: custom-scheduler
#      livenessProbe:
#        httpGet:
#          host: 127.0.0.1
#          path: /healthz
#          port: 10251
#          scheme: HTTPS
#        initialDelaySeconds: 15
#      readinessProbe:
#        httpGet:
#          host: 127.0.0.1
#          path: /healthz
#          port: 10251
#      resources:
