apiVersion: apps/v1
kind: Deployment
metadata:
  name: acloud-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: acloud-deployment
  template:
    metadata:
      labels:
        app: acloud-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
          ports:
            - containerPort: 80
      resources:
