---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 4
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      labels:
        app: my-deployment
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.19.2
          ports:
            - containerPort: 80
      resources:
