apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: my-deploy # The label for the deployment
  template:
    metadata:
      labels:
        app: my-deploy # The label for the pod in the template MUST MATCH the label for the deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.1
          ports:
            - containerPort: 80
      resources:
---
kind: Service
apiVersion: v1
metadata:
  name: hello-world
spec:
  selector:
    app: my-deployment
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 32001
  type: NodePort
