apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx        # The selectors MUST match the labels in the POD spec below
      type: nginx-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx      # The labels MUST match the selectors in the Deployment spec above
        type: nginx-pod
    spec:
      containers:
      - image: nginx
        name: nginx-container
        resources: {}
status: {}
