apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-app
    location: NorthAmerica
    type: front-end
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx:1.17.10-alpine
        name: nginx-pod
        resources:
        ports:
        - containerPort: 80
