apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: test-deploy
  name: test-deploy
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: silly-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: silly-pod
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
