---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-deployment
  labels:
    app: ping-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-deployment
  template:
    metadata:
      labels:
        app: ping-deployment
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: ['sh', '-c', 'ping 1.1.1.1']
