---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-http
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5    # Wait 5 seconds before starting probe
      periodSeconds: 5          # Run probe every 5 seconds
