apiVersion: v1
kind: Pod
metadata:
  name: onfailure-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: alpine
    image: alpine
    #command: ['sh', '-c', 'sleep 10']
    command: ['sh', '-c', 'sleep 10; this is a bad command that will fail bigly']
