apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-svc-example
spec:
  replicas: 4
  selector:
    matchLabels:
      app: svc-example
  template:
    metadata:
      labels:
        app: svc-example
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc-clusterip
spec:
  type: ClusterIP
  selector:
    app: svc-example
  ports:
    - name: http
      protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 80 # The port the service is routing to on the backend Pods.
