apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app":"test-daemonset"},"name":"test-daemonset","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"test-daemonset"}},"template":{"metadata":{"labels":{"app":"test-daemonset"}},"spec":{"containers":[{"image":"alpine","imagePullPolicy":"Always","name":"alpine-container"}]}}}}
  creationTimestamp: "2022-01-04T03:40:40Z"
  generation: 1
  labels:
    app: test-daemonset
  name: test-daemonset
  namespace: default
  resourceVersion: "201958"
  uid: 4c79dc0b-ef98-431d-bc98-876d064ce304
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-daemonset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-daemonset
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        name: alpine-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
