---
- hosts: all
  become: true

  handlers:
  - name: containerd status
    service: name=containerd state=restarted

  - name: Restart SSH
    service:
      name: sshd
      state: restarted

  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - net-tools
      - vim
      - ansible
      - ansible-doc
      - ansible-lint
      - yamllint
      - sshpass
      - chrony
      - etcd-client
      - jq
      - traceroute
      - bridge-utils
      - httping
      - sysstat

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      #repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      repo: deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /
      state: present

  - name: Install container runtime crio and its dependecies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - cri-o
      - cri-o-runc
    notify:
      - containerd status

  - name: Load netfilter kernel module
    modprobe:
      name: "{{ item }}"
      state: present
    with_items:
      - overlay
      - br_netfilter

        #- name: Update /etc/containerd/config.toml
        #shell: containerd config default | sudo tee /etc/containerd/config.toml

  - name: Restart containerd service
    service:
      name: containerd
      state: restarted

  - name: Set sysctl
    sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: true
      state: present
      #reload: yes
    with_items:
      - net.ipv4.ip_forward
      - net.bridge.bridge-nf-call-iptables
      - net.bridge.bridge-nf-call-ip6tables
    notify:
      - containerd status

#  - name: Alternate sysctl 1
#    command: "{{ item }}"
#    with_items:
#      - sysctl -w net.ipv4.ip_forward=1
#      - sysctl -w net.bridge.bridge-nf-call-iptables=1
#      - sysctl -w net.bridge.bridge-nf-call-ip6tables=1
#    notify:
#      - containerd status

  - name: Enable Chrony
    service:
      name: chrony
      state: started
      enabled: true

  - name: Set timezone to America/Denver
    timezone:
      name: America/Denver

  - name: Allow ssh to host
    lineinfile:
      path: /etc/ssh/sshd_config
      regex: '^PasswordAuthentication'
      line: 'PasswordAuthentication yes'
    notify:
      - Restart SSH

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add /etc/host entries
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    with_items:
      - '10.0.1.130 kube-master'
      - '10.0.1.131 kube-1'
      - '10.0.1.132 kube-2'
      - '10.0.1.133 kube-3'
      - '10.0.1.134 kube-4'

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - kubelet=1.19.1-00   # =1.16.15-00
        - kubeadm=1.19.1-00   # =1.16.15-00
        - kubectl=1.19.1-00   # =1.16.15-00

  - name: Mark Docker and Kubernetes Packages Hold
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
      - kubelet
      - kubeadm
      - kubectl
      - containerd.io

  - name: Create /etc/default/kubelet file
    file:
      path: /etc/default/kubelet
      state: touch
      mode: '0644'

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
      # line: KUBELET_EXTRA_ARGS=--node-ip=10.0.1.110

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: true
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="192.168.60.10" \
             --apiserver-cert-extra-sans="192.168.60.10"  --node-name k8s-master \
             --pod-network-cidr=192.168.0.0/16

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
      - mkdir -p /home/vagrant/.kube
      - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
      - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Add set -o vi to my .bashrc
    become: false
    lineinfile:
      dest: ~/.bashrc
      regexp: '^set -o vi'
      line: set -o vi

  - name: Set vim as my default editor
    become: false
    lineinfile:
      dest: ~/.bashrc
      line: export EDITOR=vim
      insertbefore: 'set -o vi'

  - name: Setup kubeconfig for vagrant user
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant

  - name: Install calico pod network
    become: false
    shell: kubectl create -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml

  - name: Install Kubernetes Dashboard
    become: false
    shell: kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Create kubectl/bash completion
    shell: kubectl completion bash > /tmp/kubectl

  - name: Move kubectl shell completion file to correct location
    shell: mv /tmp/kubectl /etc/bash_completion.d/kubectl
    become: true

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Remove unnecessary apt repo files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/apt/sources.list.d/kubernetes.list

        #- name: Copy over VIM stuff
        #copy:
        #src: "{{ item }}"
        #dest: /home/vagrant
        #with_items:
        #- /home/feathrex/.vimrc
        #- /home/feathrex/.vim
