---
- hosts: all
  become: true

  handlers:
  - name: docker status
    service: name=docker state=started

  - name: Restart SSH
    service:
      name: sshd
      state: restarted

  - name: Restart docker
    service:
      name: docker
      state: restarted

  - name: Daemon Reload
    systemd:
      daemon_reload: true

  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - net-tools
      - sshpass
      - chrony
      - tree
        #- virtualbox-guest-utils
        #- virtualbox-guest-dkms

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Add apt repository for Docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker and its dependecies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        #- docker-ce=5:19.03.14~3-0~ubuntu-focal
        #- docker-ce-cli=5:19.03.14~3-0~ubuntu-focal
        #- containerd.io=1.4.3-1
      - docker-ce=5:20.10.7~3-0~ubuntu-focal
      - docker-ce-cli=5:20.10.7~3-0~ubuntu-focal
      - containerd.io=1.4.6-1

  - name: Update /etc/docker/daemon.json to use systemd
    copy:
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: 0755
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
        },
          "storage-driver": "overlay2",
          "storage-opts": [
            "overlay2.override_kernel_check=true"
          ]
        }
    notify:
      - Daemon Reload
      - Restart docker

  - name: Enable Chrony
    service:
      name: chrony
      state: started
      enabled: true

  - name: Set timezone to America/Denver
    timezone:
      name: America/Denver

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add /etc/host entries
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
      state: present
    with_items:
      - '10.0.1.121 controller-01'
      - '10.0.1.122 controller-02'
      - '10.0.1.123 controller-03'
      - '10.0.1.124 worker-01'
      - '10.0.1.125 worker-02'
      - '10.0.1.126 worker-03'
      - '10.0.1.127 worker-04'
      - '10.0.1.119 kubelb-01'
      - '192.168.45.121 controller-01-priv'
      - '192.168.45.122 controller-02-priv'
      - '192.168.45.123 controller-03-priv'
      - '192.168.45.124 worker-01-priv'
      - '192.168.45.125 worker-02-priv'
      - '192.168.45.126 worker-03-priv'
      - '192.168.45.127 worker-04-priv'
      - '192.168.45.119 kubelb-01-priv'

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - kubelet=1.19.9-00   # =1.16.15-00
        - kubeadm=1.19.9-00   # =1.16.15-00
        - kubectl=1.19.9-00   # =1.16.15-00
        #- kubelet=1.20.0-00
        #- kubeadm=1.20.0-00
        #- kubectl=1.20.0-00
        #- kubelet=1.21.2-00   # =1.16.15-00
        #- kubeadm=1.21.2-00   # =1.16.15-00
        #- kubectl=1.21.2-00   # =1.16.15-00


  - name: Mark Docker and Kubernetes Packages Hold
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    with_items:
      - kubelet
      - kubeadm
      - kubectl
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Create /etc/default/kubelet file
    file:
      path: /etc/default/kubelet
      state: touch
      mode: '0644'

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Allow ssh to host
    lineinfile:
      path: /etc/ssh/sshd_config
      regex: '^PasswordAuthentication'
      line: 'PasswordAuthentication yes'
    notify:
      - Restart SSH

  - name: Create kubectl/bash completion
    shell: kubectl completion bash > /tmp/kubectl

  - name: Move kubectl shell completion file to correct location
    command: mv /tmp/kubectl /etc/bash_completion.d/kubectl
    become: true

  - name: Add set -o vi to my .bashrc
    become: false
    lineinfile:
      dest: ~/.bashrc
      regexp: '^set -o vi'
      line: set -o vi

  - name: Set vim as my default editor
    become: false
    lineinfile:
      dest: ~/.bashrc
      line: export EDITOR=vim
      insertbefore: 'set -o vi'

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: true
      state: restarted

  - name: Disable multipathd Service
    service:
      name: multipathd
      state: stopped
      enabled: false

  - name: Copy the join command to server location
    copy: src=join-command dest=/tmp/join-command.sh mode=0755

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh

  - name: Update /var/lib/kubelet/kubeadm-flags.env
    lineinfile:
      path: /var/lib/kubelet/kubeadm-flags.env
      regexp: '^KUBELET_KUBEADM_ARGS'
      line: KUBELET_KUBEADM_ARGS="--network-plugin=cni --cgroup-driver=systemd --pod-infra-container-image=k8s.gcr.io/pause:3.4.1"

  - name: Start Proxy
    shell: kubectl proxy --address='0.0.0.0' --accept-hosts='^*$' &

  - name: Remove unnecessary apt repo files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
      - /etc/apt/sources.list.d/kubernetes.list
