apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
    tier: front-end
spec:
  containers:
    - name: nginx
      image: nginx
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do sleep 1000; done']
