apiVersion: v1
kind: Pod
metadata:
  name: multi-nginx-busy-pod
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ['/bin/sh', '-c', 'sleep 2d']
    - name: nginx-container
      image: nginx
