apiVersion: v1
kind: Pod
metadata:
  name: random-number-gen
spec:
  containers:
    - image: alpine
      name: alpine-pod
      command: ["/bin/sh", "-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
      volumeMounts:
        - name: data-volume
          mountPath: /opt

  volumes:
    - name: data-volume
      hostPath:
        path: /data
        type: Directory
