apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: elastic
    tier: node
  name: elasticsearch
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
        tier: node
    spec:
      containers:
        - image: k8s.gcr.io/fluentd-elasticsearch:1.20
          imagePullPolicy: IfNotPresent
          name: fluentd-elasticsearch
