---
- hosts: all
  become: true
  tasks:

  - name: Update /etc/crictl.yaml
    lineinfile:
      path: /etc/crictl.yaml
      regexp: '^runtime-endpoint: '
      line: 'runtime-endpoint: unix:///run/containerd/containerd.sock'
      backrefs: true
