---
- name: generate SSH key
  hosts: all
  become: false
  gather_facts: true

  vars:
    ssh_key_filename: id_ed25519

  tasks:
    - name: generate SSH key "{{ ssh_key_filename }}"
      openssh_keypair:
        path: "~/.ssh/{{ ssh_key_filename }}"
        type: ed25519
        state: present
        force: no
      tags:
        - genkey

- hosts: all
  become: false
  gather_facts: false

  vars_files:
    - /vagrant/vars/ssh_vars.yml

  tasks:
  - name: Make sure /home/vagrant/.ssh directory exists
    file:
      path: /home/vagrant/.ssh
      state: directory
      mode: 0700
      owner: vagrant
      group: vagrant

  - name: Set authorized key taken from file
    authorized_key:
      user: vagrant
      state: present
      manage_dir: true
      # This works too using a VARIABLE for the key file
      key: "{{ lookup('file', '{{ sshkey }}') }}"
      # This works.
      #key: "{{ lookup('file', '/home/vagrant/.ssh/id_ed25519.pub') }}"
    tags:
      - deploykey
