---
# Application servers
all:
  vars:
    ansible_user: vagrant
  children:
    cluster:
      hosts:
        controller-01:
        worker-01:
        worker-02:
        worker-03:
        worker-04:
        #kubelb-01:
    workers:
      hosts:
        worker-01:
        worker-02:
        worker-03:
        worker-04:
...
