---
- hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Copy files from one host to another.
    fetch:
      src: "{{ item }}"
      dest: /tmp
      owner: root
      group: root
      mode: 0755
      remote_src: true
    with_items:
      - "/etc/kubernetes/pki/ca.crt"
      - "/etc/kubernetes/pki/ca.key"
      - "/etc/kubernetes/pki/sa.key"
      - "/etc/kubernetes/pki/sa.pub"
    when: ansible_facts['hostname'] == "controller-01"
