apiVersion: v1
kind: Pod
metadata:
  name: static-busybox
  labels:
    name: static-busybox
spec:
  containers:
  - name: static-busybox
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 1000; done']
