---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webapp
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:1.18
  schedulerName: my-scheduler
