---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    livenessProbe:
      exec:
        command: ["echo", "Hello, cruel world you fuckwits!"]
      initialDelaySeconds: 5    # Wait 5 seconds before starting probe
      periodSeconds: 5          # Run probe every 5 seconds
