#apiVersion: v1
#kind: Namespace
#metadata:
#name: alpine
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alpine
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alpine
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: alpine
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
spec:
  serviceAccountName: alpine
  containers:
  - name: salpinehpod
    image: alpine
    imagePullPolicy: Always
    stdin: true
    tty: true
    env:
    - name: HOSTIP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
