apiVersion: v1 # <-- string
kind: Pod # <-- string type of object to create
metadata:
  name: myapp-pod # <-- string
  labels: # <-- dictionary
    app: myapp
    type: front-end
    silly-name: my-dumb-pod
spec:
  containers: # <-- List/array
    - name: nginx # <-- first item in the list
      image: nginx:1.19.2
      ports:
        - containerPort: 80
  restartPolicy: OnFailure
