apiVersion: v1
kind: Pod
metadata:
  name: nodeselector-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: NotIn
                values:
                  - Small
