apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: p2-pod
  name: p2-pod
  namespace: project-hamster
spec:
  containers:
  - image: nginx:1.21.3-alpine
    name: p2-pod
  - image: busybox:1.31
    name: c2
    command: ["sh", "-c", "sleep 1d"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
