---
apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    resources:
      requests:
        cpu: "3000m"    # 3 CPU Cores
        memory: "128Mi"
      limits:
        cpu: "5000m"
        memory: "256Mi"
