apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginxWebserver
    env: test
    tier: webTier
spec:
  containers:
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    resources: {}
